import { expect, test, type Page } from '@playwright/test'
import { applyAction, startHand } from '../../src/game/engine'
import { finishedMatch } from '../fixtures/match'

async function readGame(page: Page) {
  return page.evaluate(() => JSON.parse(sessionStorage.getItem('poker-lab-session-v1')!))
}
async function terminalFixture(page: Page, winner: 0 | 1, paused = false) {
  const game = finishedMatch(winner)
  await page.addInitScript(({ game, paused }) => {
    if (!sessionStorage.getItem('poker-lab-session-v1')) {
      sessionStorage.setItem('poker-lab-session-v1', JSON.stringify(game))
      sessionStorage.setItem('poker-lab-context-v1', JSON.stringify({ sessionId: 'test-session', matchId: 'test-match', paused }))
    }
  }, { game, paused })
}

test('shows the hand result for three seconds then automatically rotates the button', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-09T00:00:00Z') })
  await page.clock.pauseAt(new Date('2026-10-09T00:00:01Z'))
  await page.goto('./')
  await expect(page.getByTestId('pot')).toHaveText('3')
  await expect(page.getByTestId('pot-odds')).toHaveText('25.0%')
  await page.getByRole('button', { name: 'Fold', exact: true }).click()
  await expect(page.getByTestId('total-hands')).toHaveText('1')
  await expect(page.getByTestId('session-hands')).toHaveText('1')
  await expect(page.getByTestId('match-score')).toContainText('0 : 0')
  await expect(page.getByTestId('auto-next')).toContainText('через 3 с')
  await page.clock.runFor(2999)
  await expect(page.locator('.hand-number')).toContainText('#001')
  await expect(page.locator('.result-net')).toBeVisible()
  await page.clock.runFor(1)
  await expect(page.locator('.hand-number')).toContainText('#002')
  await expect(page.getByLabel('AdaptiveAI: Button / Small Blind')).toBeVisible()
  expect((await readGame(page)).players.map((p: { initialStack: number }) => p.initialStack)).toEqual([199, 201])
  await expect(page.getByTestId('session-hands')).toHaveText('1')
})

test('pause survives reload and prevents transitions; resuming and manual next both work', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-09T00:00:00Z') })
  await page.clock.pauseAt(new Date('2026-10-09T00:00:01Z'))
  await page.goto('./')
  await page.getByRole('button', { name: 'Fold', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Следующая раздача', exact: true })).toBeEnabled()
  await page.clock.runFor(1000)
  await page.getByRole('button', { name: 'Пауза автоигры', exact: true }).click()
  await page.clock.runFor(5000)
  await expect(page.locator('.hand-number')).toContainText('#001')
  await page.reload()
  await expect(page.getByRole('button', { name: 'Продолжить автоигру', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByTestId('total-hands')).toHaveText('1')
  await expect(page.getByTestId('session-hands')).toHaveText('1')
  await page.clock.runFor(5000)
  await expect(page.locator('.hand-number')).toContainText('#001')
  await page.getByRole('button', { name: 'Продолжить автоигру', exact: true }).click()
  await page.clock.runFor(3000)
  await expect(page.locator('.hand-number')).toContainText('#002')
  await page.getByRole('button', { name: 'Пауза автоигры', exact: true }).click()
  await page.clock.runFor(1000)
  // Either AI has folded or Hero can now end the hand.
  const fold = page.getByRole('button', { name: 'Fold', exact: true })
  if (await fold.count()) await fold.click()
  await expect(page.getByRole('button', { name: 'Следующая раздача', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Следующая раздача', exact: true }).click()
  await expect(page.locator('.hand-number')).toContainText('#003')
})

for (const winner of [0, 1] as const) {
  test(`records ${winner === 0 ? 'Hero' : 'AI'} match win once and automatically starts 200/200 without resetting the session`, async ({ page }) => {
    await page.clock.install({ time: new Date('2026-10-09T00:00:00Z') })
  await page.clock.pauseAt(new Date('2026-10-09T00:00:01Z'))
    await terminalFixture(page, winner)
    await page.goto('./')
    await expect(page.getByRole('button', { name: 'Следующий матч', exact: true })).toBeEnabled()
    const score = winner === 0 ? '1 : 0' : '0 : 1'
    await expect(page.getByTestId('match-score')).toContainText(score)
    await expect(page.getByTestId('session-hands')).toHaveText('1')
    await page.clock.runFor(2999)
    expect((await readGame(page)).result).toBeTruthy()
    await page.clock.runFor(1)
    await expect(page.locator('.hand-number')).toContainText('#002')
    const next = await readGame(page)
    expect(next.players.map((p: { initialStack: number }) => p.initialStack)).toEqual([200, 200])
    expect(next.players.map((p: { stack: number }) => p.stack)).toEqual([198, 199])
    await expect(page.getByTestId('session-hands')).toHaveText('1')
    await expect(page.getByTestId('total-hands')).toHaveText('1')
    await page.reload()
    await expect(page.getByTestId('match-score')).toContainText(score)
    await expect(page.getByTestId('total-hands')).toHaveText('1')
  })
}

test('score reset requires confirmation, keeps history and does not re-award on reload', async ({ page }) => {
  await terminalFixture(page, 0, true)
  await page.goto('./')
  await expect(page.getByTestId('match-score')).toContainText('1 : 0')
  await page.getByRole('button', { name: 'Сбросить счёт матчей', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Отмена', exact: true }).click()
  await expect(page.getByTestId('match-score')).toContainText('1 : 0')
  await page.getByRole('button', { name: 'Сбросить счёт матчей', exact: true }).click()
  await page.getByRole('button', { name: 'Сбросить счёт', exact: true }).click()
  await expect(page.getByTestId('match-score')).toContainText('0 : 0')
  await page.reload()
  await expect(page.getByTestId('match-score')).toContainText('0 : 0')
  await expect(page.getByTestId('total-hands')).toHaveText('1')
  await expect(page.getByTestId('session-hands')).toHaveText('1')
  await page.getByRole('button', { name: /История рук/ }).click()
  await expect(page.locator('.hand-entry')).toHaveCount(1)
})

test('new session resets only the session counter; a new tab retains persistent counters', async ({ page, context }) => {
  await terminalFixture(page, 1, true)
  await page.goto('./')
  await expect(page.getByTestId('session-hands')).toHaveText('1')
  await page.getByRole('button', { name: 'Новая сессия', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Новая сессия', exact: true }).click()
  await expect(page.getByTestId('session-hands')).toHaveText('0')
  await expect(page.getByTestId('total-hands')).toHaveText('1')
  await expect(page.getByTestId('match-score')).toContainText('0 : 1')
  await page.getByRole('button', { name: 'Fold', exact: true }).click()
  await expect(page.getByTestId('session-hands')).toHaveText('1')
  await expect(page.getByTestId('total-hands')).toHaveText('2')
  const another = await context.newPage()
  await another.goto('./')
  await expect(another.getByTestId('session-hands')).toHaveText('0')
  await expect(another.getByTestId('total-hands')).toHaveText('2')
  await expect(another.getByTestId('match-score')).toContainText('0 : 1')
  await another.close()
})

test('right panel reports the acting player and street bets reset when chips enter the pot', async ({ page }) => {
  let game = applyAction(startHand(), 0, { type: 'call' })
  game = applyAction(game, 1, { type: 'check' })
  game = applyAction(game, 1, { type: 'bet', to: 4 })
  await page.addInitScript(game => sessionStorage.setItem('poker-lab-session-v1', JSON.stringify(game)), game)
  await page.clock.install({ time: new Date('2026-10-09T00:00:00Z') })
  await page.clock.pauseAt(new Date('2026-10-09T00:00:01Z'))
  await page.goto('./')
  await expect(page.getByTestId('current-street')).toHaveText('FLOP')
  await expect(page.getByTestId('pot')).toHaveText('8')
  await expect(page.getByTestId('to-call')).toHaveText('4 фишек')
  await expect(page.getByTestId('pot-odds')).toHaveText('33.3%')
  await expect(page.getByTestId('bet-1')).toHaveText('4')
  await page.getByRole('button', { name: 'Call 4', exact: true }).click()
  await expect(page.getByTestId('current-street')).toHaveText('TURN')
  await expect(page.getByTestId('pot')).toHaveText('12')
  await expect(page.getByTestId('bet-0')).toHaveText('0')
  await expect(page.getByTestId('bet-1')).toHaveText('0')
  await expect(page.getByLabel('Текущее решение')).toContainText('Решение: AdaptiveAI')
  await expect(page.getByTestId('pot-odds')).toHaveText('0%')
})

test('IndexedDB failure prevents auto advance and retry records the pending hand exactly once', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-09T00:00:00Z') })
  await page.clock.pauseAt(new Date('2026-10-09T00:00:01Z'))
  await page.addInitScript(() => {
    const original = IDBFactory.prototype.open
    Object.assign(window, { restoreDatabase: () => { IDBFactory.prototype.open = original } })
    IDBFactory.prototype.open = () => { throw new Error('Simulated IndexedDB unavailable') }
  })
  await page.goto('./')
  await page.getByRole('button', { name: 'Fold', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Автопереход остановлен')
  await page.clock.runFor(5000)
  await expect(page.locator('.hand-number')).toContainText('#001')
  await expect(page.locator('.next-hand')).toBeDisabled()
  await page.evaluate(() => (window as unknown as { restoreDatabase: () => void }).restoreDatabase())
  await page.getByRole('button', { name: 'Повторить сохранение', exact: true }).click()
  await expect(page.getByTestId('total-hands')).toHaveText('1')
  await expect(page.getByTestId('session-hands')).toHaveText('1')
  await page.clock.runFor(3000)
  await expect(page.locator('.hand-number')).toContainText('#002')
})
